using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public class Course
    {
        // This property can let Primary Key entered by user, not auto-generated by Database
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }

        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
        // If navigation propertity is not collection type，it's saying that one this.entity correspons to one Navigate.entity
        // Or it will correspons to many Navigate.entitys

    }
}